<a href="https://colab.research.google.com/github/eqmugge/MAT421/blob/main/ModuleD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
vector_row = np.array([[1, -5, 3, 2, 4]])
vector_column = np.array([[1],
                          [2],
                          [3],
                          [4]])
print("Vector shapes")
print(vector_row.shape)
print(vector_column.shape)
print("")

from numpy.linalg import norm
new_vector = vector_row.T
print("Finding vector Lnorms")
print(new_vector)
norm_1 = norm(new_vector, 1)
norm_2 = norm(new_vector, 2)
norm_inf = norm(new_vector, np.inf)
print('L_1 is: %.1f'%norm_1)
print('L_2 is: %.1f'%norm_2)
print('L_inf is: %.1f'%norm_inf)

Vector shapes
(1, 5)
(4, 1)

Finding vector Lnorms
[[ 1]
 [-5]
 [ 3]
 [ 2]
 [ 4]]
L_1 is: 15.0
L_2 is: 7.4
L_inf is: 5.0


In [10]:
#Practice Problems
import numpy as np
vector_row = np.array([[12,24,0,11,-24,18,15],
              [19,38,0,10,-31,25,9],
              [1,2,0,21,-5,3,20],
              [6,12,0,13,-10,8,5],
              [22,44,0,2,-12,17,23]])

print("Vector shapes")
print(vector_row.shape)
print("")

from numpy.linalg import norm
new_vector = vector_row.T
print("Finding vector Lnorms")
print(new_vector)
norm_1 = norm(new_vector, 1)
norm_2 = norm(new_vector, 2)
norm_inf = norm(new_vector, np.inf)
print('L_1 is: %.1f'%norm_1)
print('L_2 is: %.1f'%norm_2)
print('L_inf is: %.1f'%norm_inf)

Vector shapes
(5, 7)

Finding vector Lnorms
[[ 12  19   1   6  22]
 [ 24  38   2  12  44]
 [  0   0   0   0   0]
 [ 11  10  21  13   2]
 [-24 -31  -5 -10 -12]
 [ 18  25   3   8  17]
 [ 15   9  20   5  23]]
L_1 is: 132.0
L_2 is: 95.3
L_inf is: 120.0


In [7]:
from numpy import arccos, dot

v = np.array([[10, 9, 3]])
w = np.array([[2, 5, 12]])
theta = \
    arccos(dot(v, w.T)/(norm(v)*norm(w)))
print(theta)

[[0.97992471]]


In [16]:
#Practice Problems
from numpy import arccos, dot

v = np.array([[1], [0.001]])
w = np.array([[0.001], [1]])

theta = \
    arccos(dot(v, w.T)/(norm(v)*norm(w)))
print(theta)

[[1.56979633e+00 1.41421297e-03]
 [1.57079533e+00 1.56979633e+00]]


In [8]:
v = np.array([[0, 2, 0]])
w = np.array([[3, 0, 0]])
print(np.cross(v, w))

[[ 0  0 -6]]


In [9]:
v = np.array([[0, 3, 2]])
w = np.array([[4, 1, 1]])
u = np.array([[0, -2, 0]])
x = 3*v-2*w+4*u
print(x)

[[-8 -1  4]]


In [17]:
#Practice Problems
v = np.array([[-1, 6, 2]])
w = np.array([[2, 7, 1]])
u = np.array([[0, -4, 3]])
x = 3*v-2*w+4*u
print(x)

[[ -7 -12  16]]
